# Copyright (C) 2020-2021 Hatching B.V
# All rights reserved.

stages:
  - build
  - test

jobs:
  build:
    stage: build
    image: hatching.io/cicd-build-triage:18.04
    script:
      - make -C go

  test:
    stage: test
    image: hatching.io/cicd-build-triage:18.04
    script:
      - make test
      - make -C python test
